### ISSUE TITLE
Empty Tab/Missing Features

### ISSUE THREAD

**Issue by unlightednetting** [Bioniclegenius/NummonCalc#7]
![image](https://user-images.githubusercontent.com/4789430/86518383-bb9a8e80-bdff-11ea-8d7e-c87d32352d4c.png)

I barely have anything which I assumed was maybe the issue, but since resetting , the tab is empty

**Comment by unlightednetting** [comment]
![image](https://user-images.githubusercontent.com/4789430/86518403-dec53e00-bdff-11ea-8789-77744a4deecd.png)

**Comment by unlightednetting** [comment]
Seems to have sorted itself out now that I've played longer, refreshing and reopening was not the reason as I tried many times

**Comment by unlightednetting** [comment]
I'm back, it changed again to only have these 
![image](https://user-images.githubusercontent.com/4789430/87212618-7984b780-c2ed-11ea-8cbd-29806b9a1195.png)

**Comment by AirDur** [comment]
You don't use the mainline http://kittensgame.com/web/# .
Also, there's some fixs pending ( see #6 ).

**Comment by unlightednetting** [comment]
I see, I was using the months-behind build. It's not working on the main one either, but here's hoping that it does soon. Thank you for your work
